// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmwVqgNZyWKxIiE0jsFKxF9gOXxCFvncw',
    appId: '1:867463529801:web:0f09f31d6e613b7deb8698',
    messagingSenderId: '867463529801',
    projectId: 'dellalio-moveis-planejados',
    authDomain: 'dellalio-moveis-planejados.firebaseapp.com',
    storageBucket: 'dellalio-moveis-planejados.firebasestorage.app',
    measurementId: 'G-8ZFGW4NC9W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxy5hOlTCWsdgbsU3on_1jxOb_ddbewXo',
    appId: '1:867463529801:android:30b67ad343d6ad70eb8698',
    messagingSenderId: '867463529801',
    projectId: 'dellalio-moveis-planejados',
    storageBucket: 'dellalio-moveis-planejados.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuGRZIk_rxrkO7O3-7YRZPCCf-t-FozKA',
    appId: '1:867463529801:ios:d8cc1ca7442c345feb8698',
    messagingSenderId: '867463529801',
    projectId: 'dellalio-moveis-planejados',
    storageBucket: 'dellalio-moveis-planejados.firebasestorage.app',
    iosBundleId: 'com.example.cerebroAdm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuGRZIk_rxrkO7O3-7YRZPCCf-t-FozKA',
    appId: '1:867463529801:ios:d8cc1ca7442c345feb8698',
    messagingSenderId: '867463529801',
    projectId: 'dellalio-moveis-planejados',
    storageBucket: 'dellalio-moveis-planejados.firebasestorage.app',
    iosBundleId: 'com.example.cerebroAdm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmwVqgNZyWKxIiE0jsFKxF9gOXxCFvncw',
    appId: '1:867463529801:web:c8411a90db45a9bceb8698',
    messagingSenderId: '867463529801',
    projectId: 'dellalio-moveis-planejados',
    authDomain: 'dellalio-moveis-planejados.firebaseapp.com',
    storageBucket: 'dellalio-moveis-planejados.firebasestorage.app',
    measurementId: 'G-58XN7G7T8D',
  );
}
